# Generated by Django 3.2.6 on 2021-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercv',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='accounts/cvs/'),
        ),
    ]
