# Generated by Django 3.2.6 on 2021-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(choices=[('Active', True), ('Deactive', False)], default=True, help_text='for admins only if you want deactive job'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.BooleanField(choices=[('Active', True), ('Deactive', False)], default=True),
        ),
    ]
