# Generated by Django 3.2.6 on 2021-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Deactive')], default=True, help_text='for admins only if you want deactive job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='career_level',
            field=models.ManyToManyField(blank=True, null=True, to='job.CarrerLevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='job.Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ManyToManyField(blank=True, null=True, to='job.JobType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Deactive')], default=True),
        ),
    ]
