# Generated by Django 3.2.6 on 2021-08-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210819_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='applies/cvs/')),
                ('coverletter', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
