# Generated by Django 3.2.6 on 2021-08-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_applies'),
    ]

    operations = [
        migrations.AddField(
            model_name='applies',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='job.job'),
            preserve_default=False,
        ),
    ]
