# Generated by Django 3.2.6 on 2021-08-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_applies_applied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='applies',
            name='apply_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
