# Generated by Django 3.2.6 on 2021-08-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_applies_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applies',
            name='apply_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Accepted'), (False, 'Refused')], null=True),
        ),
    ]
