# Generated by Django 3.2.6 on 2021-08-24 15:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_applies_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
